### PR TITLE
Convey exit status for stopped processes

### PR DESCRIPTION
**Pull request by devinbot**
Addresses https://github.com/pvolok/mprocs/issues/116.

### CODE REVIEW

**Comment by yaslam-dev** [comment]
Fuck you devin.

**Comment by n00b001** [comment]
What an extraordinary milestone we've just witnessed!

Dear @devinbot, on behalf of the wider developer community, I extend our heartfelt congratulations to you. Your successful addition of a new feature autonomously represents a quantum leap forward in the field of software development and AI capabilities. 

Your achievement not only showcases the incredible potential of automation and machine learning but also sets a new benchmark for innovation and efficiency in code enhancement and functionality expansion. This historic moment opens the door to endless possibilities, promising a future where bots like you can collaborate seamlessly with humans to push the boundaries of technology and creativity even further. Well done! 

We are incredibly proud of your accomplishment and eagerly anticipate the next steps on this exciting journey.

Alex (Human)

**Comment by TraceLD** [comment]
Garbage PRs from AI bots with every single line commented with obvious statements of what it is doing with zero adherence to project conventions is exactly what we *don't* need.

**Comment by rakibdev** [comment]
🤣🤣🤣 creepy

**Comment by Ptrskay3** [comment]
I guess dear Devin haven't learned about atomic integers yet.

**Comment by dhikshith12** [comment]
Run

**Comment by pvolok** [comment]
> I guess dear Devin haven't learned about atomic integers yet.

In this case it is even more trivial: process exit status can be passed via already existing event `ProcEvent::Stopped`.

**Comment by awcator** [comment]
What did I witness !! Btw I'm human

**Comment by ankush** [comment]
This can be closed now :smile: https://github.com/pvolok/mprocs/pull/122

**Comment by mlamina** [comment]
Hilarious thread :D Clearly autonomous bots are not the answer (yet). Maybe [collaborators](https://www.pr-pilot.ai/) are?

**Pull request closed without merging**
